CREATE DATABASE LIBRARY_MANAGEMENT;
USE LIBRARY_MANAGEMENT;

CREATE TABLE BOOK_DETAILS (
    ISBN BIGINT PRIMARY KEY,
    BOOK_TITLE VARCHAR(256),
    PUBLICATION_YEAR VARCHAR(256),
    LANGUAGE VARCHAR(256),
    CATEGORY_TYPE INT UNIQUE KEY,
    BINDING_ID INT UNIQUE KEY,
    NO_OF_COPIES_ACTUAL INT,
    NO_OF_COPIES_CURRENT INT
);

CREATE TABLE BINDING_DETAILS (
    BINDING_ID INT PRIMARY KEY,
    BINDING_NAME VARCHAR(256)
);

CREATE TABLE CATEGORY_DETAILS (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(256)
);

CREATE TABLE BORROWER_DETAILS (
    BORROWER_ID INT PRIMARY KEY,
    BOOK_ID INT,
    BORROWED_FROM_DATE DATE,
    BORROWED_TO_DATE DATE,
    ACTUAL_RETURN_DATE DATE,
    ISSUED_BY INT
);

CREATE TABLE STUDENT_DETAILS (
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(256),
    SEX ENUM('M', 'F'),
    DATE_OF_BIRTH DATE,
    BORROWER_ID INT UNIQUE KEY,
    DEPARTMENT VARCHAR(256),
    CONTACT_NO INT UNIQUE KEY
);

CREATE TABLE STAFF_DETAILS (
    USER_ID INT PRIMARY KEY,
    USER_NAME VARCHAR(256),
    IS_ADMIN ENUM('YES', 'NO')
);

CREATE TABLE SHELF_DETAILS (
    SHELF_ID INT,
    FLOOR INT
);

INSERT INTO BOOK_DETAILS VALUES 
(9780131103627, 'LET US C', '2020', 'ENGLISH', 1, 1, 10, 8),
(9789389552355, 'INDIA AFTER GANDHI', '2019', 'ENGLISH', 2, 2, 5, 3);

INSERT INTO BINDING_DETAILS VALUES 
(1, 'HARDCOVER'),
(2, 'PAPERBACK');

INSERT INTO CATEGORY_DETAILS VALUES 
(1, 'PROGRAMMING'),
(2, 'HISTORY');

INSERT INTO BORROWER_DETAILS VALUES 
(101, 9780131103627, '2025-05-01', '2025-05-15', NULL, 1001),
(102, 9789389552355, '2025-05-05', '2025-05-20', '2025-05-18', 1002);

INSERT INTO STUDENT_DETAILS VALUES 
(201, 'RAHUL SHARMA', 'M', '2002-03-15', 101, 'COMPUTER SCIENCE', 9876543210),
(202, 'PRIYA SINGH', 'F', '2001-09-10', 102, 'HISTORY', 8765432109);

INSERT INTO STAFF_DETAILS VALUES 
(1001, 'MR. ARUN KUMAR', 'YES'),
(1002, 'MS. NEHA VERMA', 'NO');

INSERT INTO SHELF_DETAILS VALUES 
(1, 1),
(2, 2);

ALTER TABLE BORROWER_DETAILS MODIFY BOOK_ID VARCHAR(13);

INSERT INTO BORROWER_DETAILS VALUES  
(101, '9780131103627', '2025-05-01', '2025-05-15', NULL, 1001),
(102, '9789389552355', '2025-05-05', '2025-05-20', '2025-05-18', 1002);

ALTER TABLE BOOK_DETAILS
ADD CONSTRAINT FK_Book_Binding
FOREIGN KEY (BINDING_ID)
REFERENCES BINDING_DETAILS(BINDING_ID);

SELECT b.ISBN, b.BOOK_TITLE, bd.BINDING_NAME
FROM BOOK_DETAILS b
JOIN BINDING_DETAILS bd ON b.BINDING_ID = bd.BINDING_ID;

ALTER TABLE BOOK_DETAILS
ADD CONSTRAINT FK_Book_Category
FOREIGN KEY (CATEGORY_TYPE)
REFERENCES CATEGORY_DETAILS(CATEGORY_ID);

ALTER TABLE BORROWER_DETAILS
ADD CONSTRAINT FK_Borrower_Book
FOREIGN KEY (BOOK_ID)
REFERENCES BOOK_DETAILS(ISBN);

ALTER TABLE BOOK_DETAILS MODIFY ISBN VARCHAR(13);

SELECT bd.BORROWER_ID, bd.BOOK_ID, b.BOOK_TITLE
FROM BORROWER_DETAILS bd
JOIN BOOK_DETAILS b ON bd.BOOK_ID = b.ISBN;

ALTER TABLE STUDENT_DETAILS
ADD CONSTRAINT FK_Student_Borrower
FOREIGN KEY (BORROWER_ID)
REFERENCES BORROWER_DETAILS(BORROWER_ID);

SELECT 
    s.STUDENT_ID, 
    s.STUDENT_NAME, 
    b.BOOK_TITLE, 
    st.USER_NAME AS STAFF_NAME, 
    br.BORROWED_TO_DATE
FROM STUDENT_DETAILS s
JOIN BORROWER_DETAILS br ON s.BORROWER_ID = br.BORROWER_ID
JOIN BOOK_DETAILS b ON br.BOOK_ID = b.ISBN
JOIN STAFF_DETAILS st ON br.ISSUED_BY = st.USER_ID;


ALTER TABLE BOOK_DETAILS
ADD SHELF_ID INT;

ALTER TABLE BOOK_DETAILS
ADD CONSTRAINT FK_Book_Shelf
FOREIGN KEY (SHELF_ID)
REFERENCES SHELF_DETAILS(SHELF_ID);


UPDATE BOOK_DETAILS
SET SHELF_ID = 1
WHERE ISBN = '9780131103627';

UPDATE BOOK_DETAILS
SET SHELF_ID = 2
WHERE ISBN = '9789389552355';


SELECT 
    s.STUDENT_ID, 
    s.STUDENT_NAME, 
    b.BOOK_TITLE, 
    c.CATEGORY_NAME,
    bind.BINDING_NAME,
    sh.FLOOR AS SHELF_FLOOR,
    st.USER_NAME AS STAFF_NAME,
    br.BORROWED_FROM_DATE,
    br.BORROWED_TO_DATE,
    br.ACTUAL_RETURN_DATE
FROM STUDENT_DETAILS s
JOIN BORROWER_DETAILS br ON s.BORROWER_ID = br.BORROWER_ID
JOIN BOOK_DETAILS b ON br.BOOK_ID = b.ISBN
JOIN CATEGORY_DETAILS c ON b.CATEGORY_TYPE = c.CATEGORY_ID
JOIN BINDING_DETAILS bind ON b.BINDING_ID = bind.BINDING_ID
JOIN SHELF_DETAILS sh ON b.SHELF_ID = sh.SHELF_ID
JOIN STAFF_DETAILS st ON br.ISSUED_BY = st.USER_ID;
